# Generated by Django 4.1.7 on 2023-04-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0015_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
