# Generated by Django 3.2.4 on 2022-03-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0005_auto_20210805_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
