# Generated by Django 4.1.7 on 2023-03-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0007_contact_il_contact_location_contact_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Bülten',
                'ordering': ['email'],
            },
        ),
    ]
