# Generated by Django 4.1.7 on 2023-04-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0009_remove_contact_il_remove_contact_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['email'], 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
    ]
