# Generated by Django 4.1.7 on 2023-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0010_alter_contact_options_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Mesaj *'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Tam isim *'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon Numarası *'),
        ),
    ]
