# Generated by Django 4.1.7 on 2023-05-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0011_alter_contact_message_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='alkol',
            field=models.CharField(max_length=300, null=True, verbose_name='Alkol tüketme sıklığınız?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='boy',
            field=models.CharField(max_length=30, null=True, verbose_name='Boy'),
        ),
        migrations.AddField(
            model_name='contact',
            name='diyet_gecmisi',
            field=models.CharField(max_length=300, null=True, verbose_name='Daha önce diyet yaptınız mı? Yaptıysanız ne kadar sürede kaç kilo verdiniz?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ilaçlar',
            field=models.CharField(max_length=300, null=True, verbose_name='Kullandığınız ilaçlar?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='istenen_besinler',
            field=models.CharField(max_length=300, null=True, verbose_name='Diyette mutlaka tüketmek istiyorum dediğiniz besinler?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='istenyemen_besinler',
            field=models.CharField(max_length=300, null=True, verbose_name='Diyette asla tüketmem dediğiniz besinler?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='kahve_çay',
            field=models.CharField(max_length=300, null=True, verbose_name='Günde kaç bardak çay/kahve/bitki çayı tüketirsiniz?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='kilo',
            field=models.CharField(max_length=30, null=True, verbose_name='Kilo'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mesai',
            field=models.CharField(max_length=300, null=True, verbose_name='Çalışıyorsanız mesai saatleriniz ve evden çıkış-dönüş saatleriniz?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meseleginiz',
            field=models.CharField(max_length=30, null=True, verbose_name='Mesleğiniz'),
        ),
        migrations.AddField(
            model_name='contact',
            name='operasyonlar',
            field=models.CharField(max_length=300, null=True, verbose_name='Daha önce geçirdiğiniz bir operasyon var mı? Nedir?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='saglik_problemleri',
            field=models.CharField(max_length=300, null=True, verbose_name='Herhangi bir sağlık probleminiz var mı?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sigara',
            field=models.CharField(max_length=300, null=True, verbose_name='Sigara içiyor musunuz? Günde kaç adet?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sindirim',
            field=models.CharField(max_length=300, null=True, verbose_name='Barğırsaklarınız düzenli çalışıyor mu?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='su',
            field=models.CharField(max_length=300, null=True, verbose_name='Günde kaç bardak su tüketirsiniz?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='yatis_kalkis',
            field=models.CharField(max_length=300, null=True, verbose_name='Yatış ve kalkış saatleriniz?'),
        ),
        migrations.AddField(
            model_name='contact',
            name='yemek_saatleri',
            field=models.CharField(max_length=300, null=True, verbose_name='Sabah-öğle —akşam yemeği saatleriniz?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='özel olarak iletmek istedikleriniz?'),
        ),
    ]
