# Generated by Django 4.1.7 on 2023-05-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iletisim', '0012_contact_alkol_contact_birthday_contact_boy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='Doğum tarihi'),
        ),
    ]
