# Generated by Django 3.2.4 on 2022-03-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='decription_en',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='keys',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='title_en',
        ),
    ]
