# Generated by Django 3.2.4 on 2022-03-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20220302_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodelgaleri',
            name='image',
            field=models.FileField(upload_to='portfolio-image/', verbose_name='600x600'),
        ),
    ]
