# Generated by Django 3.2.4 on 2022-03-02 22:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfoliomodelgaleri_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='decription_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='decription_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='title_fr',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Başlık'),
        ),
    ]
