# Generated by Django 3.2.4 on 2022-03-06 18:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220306_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliomodel',
            options={'ordering': ['id'], 'verbose_name': 'portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='portfoliomodelgaleri',
            options={'ordering': ['created_date'], 'verbose_name': 'Galerie', 'verbose_name_plural': 'galeries'},
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='category',
            field=models.CharField(blank=True, max_length=40, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='decription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='decription_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Notation'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='limace'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='title',
            field=models.CharField(blank=True, max_length=40, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='title_fr',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='portfoliomodelgaleri',
            name='image',
            field=models.FileField(upload_to='portfolio-image/', verbose_name='600x325'),
        ),
    ]
