# Generated by Django 3.2.4 on 2022-03-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfoliomodel_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='decription_fr',
        ),
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='title_fr',
        ),
    ]
