# Generated by Django 4.1.7 on 2023-02-26 01:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_auto_20220320_1618"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projelerimiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=40, verbose_name="isim"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="kategori"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projelerimiz/",
                        verbose_name="image",
                    ),
                ),
                (
                    "decription",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="açıklama"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Projelerimiz",
                "verbose_name_plural": "Projelerimizs",
            },
        ),
        migrations.RenameField(
            model_name="portfoliomodelgaleri",
            old_name="drinks",
            new_name="portfolio",
        ),
        migrations.AlterField(
            model_name="portfoliomodelgaleri",
            name="image",
            field=models.ImageField(upload_to="portfolio-image/", verbose_name="resim"),
        ),
    ]
