# Generated by Django 4.1.7 on 2023-02-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_alter_portfoliomodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projelerimiz",
            options={"verbose_name": "Proje", "verbose_name_plural": "Projeler"},
        ),
    ]
