# Generated by Django 4.1.7 on 2023-02-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_projelerimiz_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projelerimiz",
            name="category",
        ),
        migrations.RemoveField(
            model_name="projelerimiz",
            name="image",
        ),
        migrations.AddField(
            model_name="portfoliomodel",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
    ]
