# Generated by Django 4.1.7 on 2023-02-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_remove_projelerimiz_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliomodel",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
