# Generated by Django 4.1.7 on 2023-02-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_portfoliomodel_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliomodelgaleri",
            name="title",
            field=models.CharField(blank=True, max_length=40, verbose_name="isim"),
        ),
    ]
