# Generated by Django 4.1.7 on 2023-04-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_portfoliomodelgaleri_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projelerimizmodelgaleri',
            name='proje',
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Projelerimiz',
        ),
        migrations.DeleteModel(
            name='ProjelerimizModelGaleri',
        ),
    ]
