# Generated by Django 4.1.7 on 2023-04-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_projelerimizmodelgaleri_proje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliomodel',
            options={'ordering': ['id'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.RenameField(
            model_name='portfoliomodel',
            old_name='decription',
            new_name='description',
        ),
    ]
