# Generated by Django 4.1.7 on 2023-04-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_category_remove_portfoliomodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.category'),
        ),
    ]
