# Generated by Django 4.1.7 on 2023-04-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_portfoliomodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='portfoliomodelgaleri',
            options={'ordering': ['created_date'], 'verbose_name': 'İmage', 'verbose_name_plural': 'İmages'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='portfoliomodelgaleri',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodelgaleri',
            name='image',
            field=models.ImageField(upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='portfoliomodelgaleri',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
