# Generated by Django 4.1.7 on 2023-04-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
