# Generated by Django 4.1.7 on 2023-04-26 05:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_category_name_alter_portfoliomodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToursModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'tour',
                'verbose_name_plural': 'tours',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ToursModelGaleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(upload_to='tours/')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ToursModelGaleri', to='portfolio.toursmodel')),
            ],
            options={
                'verbose_name': 'İmage',
                'verbose_name_plural': 'İmages',
                'ordering': ['created_date'],
            },
        ),
    ]
