# Generated by Django 4.1.7 on 2023-04-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_toursmodel_toursmodelgaleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'galeriler',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='portfoliomodelgaleri',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioModel',
        ),
        migrations.DeleteModel(
            name='PortfolioModelGaleri',
        ),
    ]
