# Generated by Django 4.1.7 on 2023-04-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_galerymodel_remove_portfoliomodelgaleri_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='galery/'),
        ),
    ]
