# Generated by Django 4.1.7 on 2023-04-28 04:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_galerymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='toursmodel',
            name='description_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toursmodel',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toursmodel',
            name='description_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toursmodel',
            name='title_de',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='toursmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='toursmodel',
            name='title_tr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
