# Generated by Django 4.1.7 on 2023-04-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_toursmodel_description_de_toursmodel_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toursmodel',
            name='description_de',
        ),
        migrations.RemoveField(
            model_name='toursmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='toursmodel',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='toursmodel',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='toursmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='toursmodel',
            name='title_tr',
        ),
        migrations.DeleteModel(
            name='GaleryModel',
        ),
    ]
