# Generated by Django 4.1.7 on 2023-04-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_remove_toursmodel_description_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toursmodel',
            options={'ordering': ['id'], 'verbose_name': 'Hizmet', 'verbose_name_plural': 'Hizmetler'},
        ),
    ]
