# Generated by Django 3.2.4 on 2022-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientopinionmodel',
            name='image',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='client-image/', verbose_name='image client 187x187'),
        ),
        migrations.AlterField(
            model_name='clientopinionmodel',
            name='company',
            field=models.CharField(blank=True, max_length=40, verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='clientopinionmodel',
            name='decription',
            field=models.TextField(max_length=400, verbose_name='La description'),
        ),
        migrations.AlterField(
            model_name='clientopinionmodel',
            name='title',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nom client'),
        ),
    ]
