# Generated by Django 4.1.7 on 2023-02-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kurumsal", "0004_hizmetler"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClientopinionModel",
        ),
    ]
