# Generated by Django 4.1.7 on 2023-02-27 00:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kurumsal", "0005_delete_clientopinionmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kazanimlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="başlık")),
                (
                    "decription",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="içerik"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kazanim",
                "verbose_name_plural": "Kazanimlar",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="hizmetler",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Hizmet",
                "verbose_name_plural": "Hizmetler",
            },
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(verbose_name="cevap"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(max_length=255, verbose_name="soru"),
        ),
        migrations.AlterField(
            model_name="hizmetler",
            name="title",
            field=models.CharField(max_length=255, verbose_name="başlık"),
        ),
    ]
