# Generated by Django 4.1.7 on 2023-04-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurumsal', '0007_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Hizmetler',
        ),
        migrations.DeleteModel(
            name='Kazanimlar',
        ),
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
