# Generated by Django 4.1 on 2022-11-25 03:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsModel",
        ),
        migrations.RemoveField(
            model_name="blogmodel",
            name="anahaber",
        ),
        migrations.RemoveField(
            model_name="blogmodel",
            name="intro_ar",
        ),
        migrations.RemoveField(
            model_name="blogmodel",
            name="intro_fa",
        ),
        migrations.RemoveField(
            model_name="blogmodel",
            name="title_ar",
        ),
        migrations.RemoveField(
            model_name="blogmodel",
            name="title_fa",
        ),
        migrations.AddField(
            model_name="blogmodel",
            name="category",
            field=models.CharField(blank=True, max_length=500, verbose_name="Bölüm"),
        ),
        migrations.AddField(
            model_name="blogmodel",
            name="more",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="ek içerikler"
            ),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="created_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="oluşturulma tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="title",
            field=models.CharField(blank=True, max_length=500, verbose_name="başlık"),
        ),
    ]
