# Generated by Django 4.1 on 2022-12-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0002_delete_newsmodel_remove_blogmodel_anahaber_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogmodel",
            old_name="intro",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="blogmodel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="blogmodel",
            name="more",
        ),
    ]
