# Generated by Django 4.1 on 2022-12-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0003_rename_intro_blogmodel_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodel",
            name="topic",
            field=models.CharField(blank=True, max_length=500, verbose_name="konu"),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="image",
            field=models.ImageField(null=True, upload_to="", verbose_name="ana resim"),
        ),
    ]
