# Generated by Django 4.1 on 2022-12-10 18:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0004_blogmodel_topic_alter_blogmodel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imageone", models.FileField(upload_to=None)),
                ("imegetwo", models.FileField(upload_to=None)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="content"
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="BlogModelContentConnection",
                        to="haber.blogmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Content",
                "verbose_name_plural": "Blog Contents",
            },
        ),
    ]
