# Generated by Django 4.1 on 2022-12-10 18:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0005_blogcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="created_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="image",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="cover image"
            ),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="read_time",
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="slug",
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="title",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="topic",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
