# Generated by Django 4.1 on 2022-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0006_alter_blogmodel_content_alter_blogmodel_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcontent",
            name="imageone",
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name="blogcontent",
            name="imegetwo",
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
