# Generated by Django 4.1 on 2022-12-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0007_alter_blogcontent_imageone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcontent",
            name="type",
            field=models.CharField(
                choices=[("video", "video"), ("image", "image")],
                default="image",
                max_length=6,
            ),
        ),
    ]
