# Generated by Django 4.1 on 2022-12-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0008_blogcontent_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogcontent",
            old_name="imegetwo",
            new_name="imagetwo",
        ),
    ]
