# Generated by Django 4.1 on 2022-12-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0009_rename_imegetwo_blogcontent_imagetwo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogmodel",
            options={
                "ordering": ["title"],
                "verbose_name": "New",
                "verbose_name_plural": "News",
            },
        ),
    ]
