# Generated by Django 4.1 on 2023-01-19 19:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haber", "0010_alter_blogmodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcontent",
            name="content_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="content"
            ),
        ),
        migrations.AddField(
            model_name="blogcontent",
            name="content_tr",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="content"
            ),
        ),
        migrations.AddField(
            model_name="blogmodel",
            name="content_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="blogmodel",
            name="content_tr",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="blogmodel",
            name="title_en",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="blogmodel",
            name="title_tr",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="blogmodel",
            name="topic_en",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="blogmodel",
            name="topic_tr",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
