# Generated by Django 4.1.7 on 2023-03-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0011_blogcontent_content_en_blogcontent_content_tr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='topic_en',
        ),
    ]
