# Generated by Django 4.1.7 on 2023-03-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0012_remove_blogcontent_content_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='content_tr',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='content_tr',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_tr',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='topic_tr',
        ),
    ]
