# Generated by Django 4.1.7 on 2023-03-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0013_remove_blogcontent_content_tr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='read_time',
        ),
    ]
