# Generated by Django 4.1.7 on 2023-04-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0014_remove_blogmodel_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=None)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BlogContentImageConnection', to='haber.blogcontent')),
            ],
            options={
                'verbose_name': 'Content İmage',
                'verbose_name_plural': 'Content İmages',
            },
        ),
    ]
