# Generated by Django 4.1.7 on 2023-04-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0015_blogcontentimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogContentImage',
        ),
    ]
