# Generated by Django 4.1.7 on 2023-04-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0016_delete_blogcontentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontent',
            old_name='imageone',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='imagetwo',
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='type',
        ),
    ]
