# Generated by Django 4.1.7 on 2023-04-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0017_rename_imageone_blogcontent_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='topic',
        ),
    ]
