# Generated by Django 4.1.7 on 2023-04-28 04:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0018_remove_blogmodel_rating_remove_blogmodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='content_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='content_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_de',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='title_tr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
