# Generated by Django 4.1.7 on 2023-04-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haber', '0019_blogmodel_content_de_blogmodel_content_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['title'], 'verbose_name': 'Blog', 'verbose_name_plural': 'BLogs'},
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='content_de',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='content_tr',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='title_tr',
        ),
    ]
